services:
  - type: web
    name: metabase
    env: docker
    plan: standard  # Must specify "standard" (1GB) or "professional" (2GB)
    memory: 1GB     # Explicitly enforce memory (Render sometimes ignores "plan")
    autoDeploy: false
    envVars:
      # --- Database (Postgres) ---
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant
          property: connectionString

      # --- Memory Limits (Critical Fix) ---
      - key: MB_JAVA_OPTS
        value: "-Xmx768m -Xms512m"  # Conservative for 1GB container
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx768m -Xms512m"  # Backup for JVM

      # --- Metabase Performance Tweaks ---
      - key: MB_JETTY_MAXTHREADS
        value: "50"  # Reduce threads to save RAM
      - key: MB_JETTY_QUEUESIZE
        value: "100" # Smaller queue size

      # --- Render Required ---
      - key: PORT
        value: "3000"

databases:
  - name: elephant
    databaseName: metabasedb
    ipAllowList: []
